# postgres
postgres:
  # host: "db" # docker
  host: "127.0.0.1" # local
  name: "postgres" 
  user: "postgres"
  port: 5432
  password: "postgres"

# http
http_server:
  address: ":8080"
  timeout: 4
  idle_timeout: 60 

# redis
redis:
  host: "redis"
  port: "6379"

# rabbitmq
rabbitmq:
  host: "rabbitmq"
  port: "5672"
  queue: "notify_queue"
